#region Copyright notice and license
// Copyright (c) 2019, SciTech Software AB
// All rights reserved.
//
// Licensed under the BSD 3-Clause License. 
// You may obtain a copy of the License at:
//
//     https://github.com/SciTechSoftware/SciTech.Rpc/blob/master/LICENSE
//
#endregion

using SciTech.Rpc.Client;
using SciTech.Rpc.Client.Internal;
using SciTech.Rpc.Pipelines.Client.Internal;
using System;
using System.Linq;

namespace SciTech.Rpc.Pipelines.Client
{
    public class PipelinesProxyProvider : RpcProxyProvider
    {
        /// <summary>
        /// Default pipelines proxy provider. Note that any proxy factories generated by this provider will
        /// not garbage collected (until process/AppDomain exit).
        /// </summary>
        public static readonly PipelinesProxyProvider Default = new PipelinesProxyProvider();

        public PipelinesProxyProvider(IRpcProxyDefinitionsProvider? proxyServicesProvider = null)
        {
            this.ProxyGenerator = new PipelinesProxyGenerator(proxyServicesProvider);
        }

        protected override IRpcProxyGenerator ProxyGenerator { get; }
    }
}
