#region Copyright notice and license
// Copyright (c) 2019, SciTech Software AB
// All rights reserved.
//
// Licensed under the BSD 3-Clause License. 
// You may obtain a copy of the License at:
//
//     https://github.com/SciTechSoftware/SciTech.Rpc/blob/master/LICENSE
//
#endregion

using SciTech.Rpc.Client;
using SciTech.Rpc.Client.Internal;
using SciTech.Rpc.Lightweight.Client.Internal;
using System;
using System.Linq;

namespace SciTech.Rpc.Lightweight.Client
{
    public class LightweightProxyProvider : RpcProxyProvider
    {
        /// <summary>
        /// Default lightweight proxy provider. Note that any proxy factories generated by this provider will
        /// not garbage collected (until process/AppDomain exit).
        /// </summary>
        public static readonly LightweightProxyProvider Default = new LightweightProxyProvider();

        public LightweightProxyProvider(IRpcProxyDefinitionsProvider? proxyServicesProvider = null)
        {
            this.ProxyGenerator = new LightweightProxyGenerator(proxyServicesProvider);
        }

        protected internal override IRpcProxyGenerator ProxyGenerator { get; }
    }
}
