using SciTech.Rpc.Client;
using SciTech.Rpc.Client.Internal;
using SciTech.Rpc.NetGrpc.Client.Internal;
using System;

namespace SciTech.Rpc.NetGrpc.Client
{
    public class NetGrpcProxyProvider : RpcProxyProvider
    {
        /// <summary>
        /// Default gRPC proxy provider. Note that any proxy factories generated by this provider will
        /// not garbage collected (until process/AppDomain exit).
        /// </summary>
        public static readonly NetGrpcProxyProvider Default = new NetGrpcProxyProvider();

        public NetGrpcProxyProvider(IRpcProxyDefinitionsProvider? proxyServicesProvider = null)
        {
            this.ProxyGenerator = new GrpcProxyGenerator(proxyServicesProvider);
        }

        protected internal override IRpcProxyGenerator ProxyGenerator { get; }
    }
}
